version: '3.8'
services:
  enrich:
    build:
      context: .
      dockerfile: Dockerfile
    # command: 'php artisan serve --host=0.0.0.0 --port=8080'
    # restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    # ports:
    #   - 80:8080
    networks:
      - mynet
    depends_on:
      - main_db
      - library_db

  nginx:
    image: nginx:alpine
    container_name: nginx
    # restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/ssl/:/etc/nginx/ssl/
    networks:
      - mynet
  main_db:
    image: 'mariadb:latest'
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata/main:/var/lib/mysql
    ports:
      - 33063:3306
    networks:
      - mynet

  library_db:
    image: 'mariadb:latest'
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata/library:/var/lib/mysql
    ports:
      - 33064:3306
    networks:
      - mynet
  phpmyadmin:
    image: 'phpmyadmin:latest'
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mynet

networks:
  mynet:
    driver: bridge