version: '3.8'
services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php -S 0.0.0.0:8080 -t public/'
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - user_db

  user_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - user_db

  user_db:
    image: 'mariadb:latest'
    environment:
      MYSQL_DATABASE: user
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306