version: '3.8'
services:
  user:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php -S 0.0.0.0:8080 -t public/'
    volumes:
      - .:/app
    ports:
      - 80:8080
    depends_on:
      - main_db
      - library_db

  main_db:
    image: 'mariadb:latest'
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata/main:/var/lib/mysql
    ports:
      - 33063:3306

  library_db:
    image: 'mariadb:latest'
    environment:
      MYSQL_DATABASE: library
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata/library:/var/lib/mysql
    ports:
      - 33064:3306
  phpmyadmin:
    image: 'phpmyadmin:latest'
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1